Fix error message on loading file with chart
esrlabs/chipmunk pull request #1183
Opened 2021-05-24 14:59 UTC by fur-gan

2021-05-28 07:55 UTC, DmitryAstafyev commented
@fur-gan Hi!
I **cannot** confirm an issue. Tested on mac/linux/windows - all works.

2021-05-28 07:55 UTC, DmitryAstafyev requested changes

2021-05-28 07:55 UTC, DmitryAstafyev commented on application/client.core/src/tsconfig.app.json
> +    "typeRoots": ["../node_modules/@types"],
I would not do this as soon as our client isn't node application

2021-05-28 07:56 UTC, DmitryAstafyev commented
Maybe this issue is related to your local configuration?

2021-05-28 10:14 UTC, fur-gan commented
> Maybe this issue is related to your local configuration?

That could be, I will check

2021-05-31 07:45 UTC, fur-gan commented
Yeah, seems like this was also an issue of my internal settings. It's related to the path not being recognized with '/' and works as soon as I replace the '/' with '\\'

2021-05-31 07:45 UTC, closed without merging