Support sending messages on serial connection
esrlabs/chipmunk pull request #1501
Opened 2022-09-15 07:55 UTC by fur-gan

2022-09-15 18:17 UTC, DmitryAstafyev requested changes

2022-09-15 18:17 UTC, DmitryAstafyev commented on application/client/src/app/ui/elements/transport/details/serial/component.ts
> +
id = "stdin" was for commands as soon as it was sending to `stdin` on child process )
It isn't an error, but just could confuse developer (even you in a couple of months)

2022-09-15 18:17 UTC, DmitryAstafyev commented on application/apps/indexer/sources/src/serial/serialport.rs
> +    }
I am not sure, but here you get as input `String` and after you "put" this string as bytes into buffer.
But... bellow in `income` income you gets bytes and convert it into string... Looks a little bit wierd. In general it looks like it:
- FE -> Rust:  sends bytes
- Rust (income method): convert bytes to string
- Rust (income method): send string into `write_stream`
- Rust (LineCodec / encode): convert string to bytes and write into buffer

If we are writing bytes into buffer, does it make sense to convert it into string?

2022-09-16 10:45 UTC, DmitryAstafyev approved these changes

2022-09-20 08:01 UTC, marcmo approved these changes

2022-09-20 08:17 UTC, merged