[WIP] Add contribution guide.
esrlabs/chipmunk pull request #1762
Opened 2023-04-09 14:06 UTC by sudeeptarlekar

Added contribution guide for new user.

2023-04-09 20:20 UTC, sudeeptarlekar commented
@DmitryAstafyev can you please review.
cc: @marcmo 

Thanks in advance

2023-04-10 08:13 UTC, DmitryAstafyev requested changes
In general make sense to add section about checking of code. Like "before creating of pull-request you should:":
- make sure, there are no issues related to `TypeScript`: `rake lint:all`. This command will check all `TypeScript` related parts of application
- make sure, there are no issues related to `Rust`: `rake clippy:all`. This command will check of `Rust` related parts of application
- make sure, basic tests are good with `rake test:all`

2023-04-10 08:13 UTC, DmitryAstafyev commented on contribution.md
> +and frontend app is built using Electron JS.
I would add here, something like
### Completed build / rebuild
Completed build/rebuild could be done with 
```
rake developing:clean_rebuild_all
```
We are recommend use this command for the first time of building and also in cases when instance of chipmunk was updated/rebased.

2023-04-10 08:13 UTC, DmitryAstafyev commented on contribution.md
> +
Probably make sense to add here something like:
### Build/developing commands
Full list of commands you can see with 
```
rake -T
```
Also you can use interactive mode with starting `rake` without any arguments
![Peek 2023-04-10 10-09](https://user-images.githubusercontent.com/12843747/230857595-0d0cb497-4589-4b6e-8352-dec842cb6bcf.gif)

2023-04-13 20:24 UTC, DmitryAstafyev approved these changes

2023-04-13 20:24 UTC, merged