Add context menu for column headers for DLT files
esrlabs/chipmunk pull request #1881
Opened 2023-08-01 16:04 UTC by sudeeptarlekar

Chipmunk2 has an ability to colorise the columns as we as hide/show columns from DLT file.
Chipmunk3 is missing this feature and this PR adds back same feature.

Fixes: #1852

2023-08-10 14:22 UTC, sudeeptarlekar commented
https://github.com/esrlabs/chipmunk/assets/23317691/52099de2-a2df-404a-9eb2-38455d6b77d5

2023-08-11 13:58 UTC, DmitryAstafyev requested changes
General:
- styles are not okay: `...` icon isn't aligned vertically in the header; also an issue with aligning in the context menu on the list of headers;
- this context menu should be called by clicking on `...` and also with the context menu (right mouse click)
- no need to have there button `ok`, click outside, and `ESC` should close it as well

2023-08-11 13:58 UTC, DmitryAstafyev commented on application/client/src/app/ui/views/workspace/headers/menu/template.html
> +            <li [attr.class]="'color'"
```
[attr.class]="'color'"
```
no need to link it dynamically. Can be just 
```
class="color"
```

2023-08-11 13:58 UTC, DmitryAstafyev commented on application/client/src/app/ui/views/workspace/headers/menu/template.html
> +            [attr.class]="'column'"
no need to link it dynamically. Can be just

```
[attr.class]="'column'"
```
can be
```
class="column"
```

2023-08-11 13:58 UTC, DmitryAstafyev commented on application/client/src/app/ui/views/workspace/headers/menu/component.ts
> +    @Input() public header!: string;
`header` is this used somewhere?

2023-08-11 13:58 UTC, DmitryAstafyev commented on application/client/src/app/ui/views/workspace/headers/component.ts
> +                    header: this.ngMouseOverHeader,
`header` is this used in child component?

2023-08-11 13:58 UTC, DmitryAstafyev commented on application/client/src/app/ui/views/workspace/headers/component.ts
> +    }
Tracking of mouse over and leave are quite expensive. Please, try to get rid of it. If you need `header` on event `click` you are able to get it with click event and no needs to track it during mouse movements.

2023-08-11 13:58 UTC, DmitryAstafyev commented on application/client/src/app/ui/views/workspace/headers/component.ts
> +    }
To show/hide `...` on header you can use `css`, with `::hover` 
```
& .header{
    & mat-icon {
       display: none;
    }
    &:hover {
    & mat-icon {
       display: block;
    }
    }
}
```

2023-09-04 14:56 UTC, DmitryAstafyev requested changes

2023-09-04 14:56 UTC, DmitryAstafyev commented on application/client/src/app/schema/render/columns.ts
> +                color: '#FFFFFF',
please take color from `scheme` (`@ui/styles/colors.ts`)

2023-09-04 14:56 UTC, DmitryAstafyev commented on application/client/src/app/ui/views/workspace/headers/component.ts
>              .map((h) => new RenderedHeader(h));
I think here can be a problem. Property `headers` in `html` uses index of header to update its properties (`visibility` and `width`), but `index` can be changed... for example, you have at initianal state columns
```
column - index
a - 0
b - 1
c - 2
d - 3
e - 4
```
At some moment user hides column `b` and you will get
```
column - index
a - 0
c - 1
d - 2
e - 3
```
Indexes of columns c, d, and e are now changed...it's different in view and controller

2023-09-04 14:56 UTC, DmitryAstafyev commented on application/client/src/app/ui/views/workspace/headers/menu/template.html
> +            (click)="ngOnCheckboxClick($event, i)">
looks like we need `uuid` of each column to correctly bind it between view and controller or static `index` (as property in header description)

2023-09-04 14:56 UTC, DmitryAstafyev commented on application/client/src/app/ui/views/workspace/headers/menu/component.ts
> +        event.stopPropagation();
please use tools from `@ui/env/dom`... there is method `stop`

2023-09-04 14:56 UTC, DmitryAstafyev commented on application/client/src/app/ui/views/workspace/headers/template.html
>        *ngFor="let header of headers; let i = index"
looks like we need `uuid` of each column to correctly bind it between view and controller or static `index` (as property in header description)

2023-09-04 14:56 UTC, DmitryAstafyev commented on application/client/src/app/ui/views/workspace/headers/styles.less
> +    // }
please, remove, if isn't needed

2023-09-04 14:56 UTC, DmitryAstafyev commented on application/client/src/app/ui/views/workspace/headers/component.ts
> +    public ngMore: string = 'more_horiz';
no need to have it as a property, just put a value of it into `html` directly... that's not dynamic property

2023-09-04 14:56 UTC, DmitryAstafyev commented on application/client/src/app/schema/render/columns.ts
> +        this.headers[column].color = (color === 'rgba(0,0,0,0)') ? '#FFF' : color;
Please do not hardcode values of colors. Use theme/scheme from `@ui/styles/colors`

2023-09-06 12:11 UTC, sudeeptarlekar commented
@DmitryAstafyev resolved all resizing issues, pls review again.
Thanks in advance.

2023-09-14 21:06 UTC, DmitryAstafyev commented
replaced with #1904

2023-09-14 21:06 UTC, closed without merging