Commit working code
esrlabs/chipmunk pull request #2061
Opened 2024-07-24 11:52 UTC by itsmesamster

2024-08-28 12:37 UTC, DmitryAstafyev requested changes

2024-08-28 12:37 UTC, DmitryAstafyev commented on application/apps/rustcore/ts-bindings/spec/session.search.spec.ts
> +import * as path from 'path';
also unused

2024-08-28 12:37 UTC, DmitryAstafyev commented on application/apps/rustcore/ts-bindings/spec/session.benchmark.spec.ts
> +/// <reference path="../node_modules/@types/node/index.d.ts" />
by the way, can be removed. It's rudiment from times when we were using ts-jasmine

2024-08-28 12:37 UTC, DmitryAstafyev commented on application/apps/rustcore/ts-bindings/spec/session.benchmark.spec.ts
> +                        let home_dir = (process.env as any)['SH_HOME_DIR'];
Potential bug. Case if `home_dir` doesn't have the correct value (at least not an empty string) isn't handled

2024-08-28 12:37 UTC, DmitryAstafyev commented on application/apps/rustcore/ts-bindings/spec/session.benchmark.spec.ts
> +                        const search = session.getSearch();
`session.getSearch()` can return `Error`. Case isn't handeled

2024-08-28 12:37 UTC, DmitryAstafyev commented on application/apps/rustcore/ts-bindings/spec/session.benchmark.spec.ts
> +                            case 'Observe - grab content (text)':
Not good solution make selection based on name of test. `alias` here isn't like `id` or `uuid`, but it's name. Probably makes more sense to check by property name at least:
```
                  "test4": {  // <== better to use
                  ^^^^^^
                        "alias": "Stream - startup measurement", // better rename to "name" or "title"
                        "id" | "alias": "SOME_UNIQUE_ID" // another approach to add addition field
                        "file": "",
                        "expectation_ms": 1000
                    }
```
But in any way we cannot do like it
```
case 'Observe - grab content (text)':
```
Constants should be used instead
```
case BENCH_TEST_CASE_A:
```
You can create a list of references at some specific place. Hardcoding IDs/UUIDs/Aliases - not good idea

2024-08-28 12:37 UTC, DmitryAstafyev commented on application/apps/rustcore/ts-bindings/spec/session.benchmark.spec.ts
> +                                break;
you are leaving a test without closing `session` which was created above at line 42

2024-08-28 12:37 UTC, DmitryAstafyev commented on application/apps/rustcore/ts-bindings/spec/session.benchmark.spec.ts
> +                                break;
you are leaving a test without closing `session` which was created above at line 42

2024-08-28 12:37 UTC, DmitryAstafyev commented on application/apps/rustcore/ts-bindings/spec/session.benchmark.spec.ts
> +                                break;
exit from test without closing `session` created on line 42. Also sessions created in this block aren't closed

2024-08-28 12:37 UTC, DmitryAstafyev commented on application/apps/rustcore/ts-bindings/spec/session.benchmark.spec.ts
> +                        finish(undefined, done, new Error(`Failed to complete test "${testName}" due to error: ${err instanceof Error ? err.message : err}`));
ambiguous situation. "Throwout" can occur when creating a session, which requires its preliminary closure

2024-08-28 12:37 UTC, DmitryAstafyev commented on application/apps/rustcore/ts-bindings/spec/session.benchmark.spec.ts
> +                        const search = session.getSearch();
In general, this block of code 
```
                        const session = await Session.create();
                        session.debug(true, testName);

                        const stream = session.getStream();
                        if (stream instanceof Error) throw stream;

                        const events = session.getEvents();
                        if (events instanceof Error) throw events;

                        const search = session.getSearch();
                        if (search instanceof Error) throw events;
```
Can be extracted into standalone function. Maybe makes sense also update/refactor others tests.
```
async function getTestSessionEnv(testName: string): Promise<{
    session: Session;
    events: ISessionEvents;
    stream: SessionStream;
    search: SessionSearch;
}> {
    const session = await Session.create();
    session.debug(true, testName);

    const stream = session.getStream();
    if (stream instanceof Error) {
        await session.destroy();
        return Promise.reject(stream);
    }

    const events = session.getEvents();
    if (events instanceof Error) {
        await session.destroy();
        return Promise.reject(events);
    }

    const search = session.getSearch();
    if (search instanceof Error) {
        await session.destroy();
        return Promise.reject(search);
    }

    return { session, events, search, stream };
}

```
This function can be called each time as soon as you need session and its dependencies (events, search, stream)

Probably make sense to create this function in `common` to reused it not only in benchmarks tests, but in regulars also

2024-08-28 12:37 UTC, DmitryAstafyev commented on application/apps/rustcore/ts-bindings/spec/session.indexes.spec.ts
> +import { createSampleFile, finish, performanceReport, setMeasurement, runner } from './common';
`performanceReport`, `setMeasurement` are unused

2024-08-28 12:37 UTC, DmitryAstafyev commented on application/apps/rustcore/ts-bindings/spec/session.indexes.spec.ts
> +
rudiments. Aren't used

2024-08-28 12:37 UTC, DmitryAstafyev commented on application/apps/rustcore/ts-bindings/spec/session.observe.spec.ts
> +import * as path from 'path';
Aren't used

2024-08-28 12:37 UTC, DmitryAstafyev commented on .github/workflows/benchmarks.yml
> +            fs.appendFileSync(process.env.GITHUB_ENV, `PR_REPO=${PR_REPO}\n`);
is it possible to move script into file? Workflow in general very complicated, would be nice to have a way to make it more simple at least with extracting some scripts (bash, js etc) into files

2024-09-09 07:45 UTC, DmitryAstafyev approved these changes

2024-09-09 07:46 UTC, DmitryAstafyev commented
@itsmesamster great job Sameer! Let's also consider new build CLI sys to run benchmarks and let it go

2024-09-09 14:21 UTC, DmitryAstafyev commented
@AmmarAbouZor in the scope of this PR we would need an additional build CLI command. Right now we have the command `cargo chipmunk test [TARGET]` (targets: core, shared, binding, wrapper, wasm, client, updater, app, cli). But we would need a custom js test runner to replace this (with ruby):

``` ruby
Shell.sh "#{Paths::JASMINE} spec/build/spec/session.#{spec}.spec.js"
```

To something like this (with CLI):
```shell
cargo chipmunk test bindings --custom=full_path/spec/build/spec/benchmarks.spec.js
```
Could you please take care of it as soon as you will have some time?

2024-09-11 12:00 UTC, AmmarAbouZor commented
Hi @DmitryAstafyev @itsmesamster 
Selecting custom specs is implemented in CLI tool. Now it's possible to specify one or multiple tests as following: 
* `cargo chipmunk test wrapper -s spec/build/spec/session.jobs.spec.js`: Runs single specification.
* `cargo chipmunk test wrapper -s spec/build/spec/session.jobs.spec.js -s spec/build/spec/session.search.spec.js`: Runs multiple specifications.

I've increased the version of the tool and added the change to the CHANGELOG as well.

2024-09-17 11:43 UTC, merged