Protocol based on serde
esrlabs/chipmunk pull request #2161
Opened 2024-11-28 07:39 UTC by DmitryAstafyev

Implementation of protocol for communication between `rust` and `nodejs` based on `serde` + `bincode`.

2025-01-02 15:16 UTC, AmmarAbouZor requested changes
This looks great :clap: 

I've found minor issues and added some suggestions.

I'll provide the needed changes on the build CLI tool once the other PR is merged and master is merged here.

There is another point about [Macros Hygiene](https://doc.rust-lang.org/reference/macros-by-example.html#hygiene) that can be adjusted (optionally since the macro are for internal use only). But if we want to make the macro hygiene we may need to use full paths on every type inside the macros up to `$crate::` for crate types or `::std::` for rust standard library types

2025-01-02 19:23 UTC, DmitryAstafyev commented on application/apps/protocol/test.sh
> +rake bindings:test:protocol
yes, sure... will do it as soon as build cli will be updated

2025-01-02 19:32 UTC, DmitryAstafyev commented on application/apps/protocol/src/err.rs
> +pub enum E {
I understand yor point about using single-letter type names not being a common practice, I believe it fits well in this case due to the small size of the crate. The crate consists of only a few files, and `E` is the only error type defined. This makes the code concise, as we can simply write `Result<..., E>` instead of `Result<..., Error/ProtocolErr/ProError/...>` or a longer name.

Considering limited scope and simplicity of the crate, the single-letter name improves readability. And I really don't expect, this crate will growup to have some other type for error. But... if it will happen - sure, it should be changed.

2025-01-03 07:40 UTC, AmmarAbouZor commented on application/apps/indexer/stypes/Cargo.toml
> +[features]
I think we can leave it as it is, since this an opinionated point where there is no absolute right or wrong answer :+1:

2025-01-03 07:45 UTC, AmmarAbouZor approved these changes
This looks amazing, great job! :100:

I'll provide the needed implementation on the build CLI tool and add them to this PR ASAP

2025-01-03 08:59 UTC, AmmarAbouZor commented
* Changes on the Build CLI to include building protocol on test commands are implemented
* Unit tests are extended to ensure needed build jobs are included on test commands
* Integration tests are adjusted to ensure that protocol is built and cleaned properly
* Temp fix in CI check is removed
* Generated ts files are included as well since they will be rewritten on every build run and the automatic formatting and comments will be rewritten

CI is failing now because it still using the previous Tool version and not using the latest one. [link](https://github.com/esrlabs/chipmunk/actions/runs/12595124844/job/35103787932?pr=2161#step:11:9)
@itsmesamster Could you please have a look on it?

2025-01-03 11:13 UTC, AmmarAbouZor commented
@DmitryAstafyev I've fixed generating typescript files on each test call by adding the feature `test_and_gen` to the conditional attributes, changing `cfg_attr(test,...)` to `cfg_attr( all(test, feature = "test_and_gen"),` on each type

Then I ran into an issue that the prop tests will be triggered each time we want to generate new types, so I marked them is ignored to be ran explicitly with the `--ignored` flag on `cargo test`. Alternatively, we can introduce another feature `prop_tests` and run the tests on it.

2025-01-06 17:58 UTC, merged